// Theme config for FlexColorScheme version 7.1.x. Make sure you use
// same or higher package version, but still same major version. If you
// use a lower package version, some properties may not be supported.
// In that case remove them after copying this theme to your app.
theme: FlexThemeData.light(
  colors: const FlexSchemeColor(
    primary: Color(0xffbf0028),
    primaryContainer: Color(0xffffdad8),
    secondary: Color(0xff324151),
    secondaryContainer: Color(0xffffdbcf),
    tertiary: Color(0xff805159),
    tertiaryContainer: Color(0xff95f0ff),
    appBarColor: Color(0xffffdbcf),
    error: Color(0xffb00020),
  ),
  surfaceMode: FlexSurfaceMode.highScaffoldLowSurface,
  blendLevel: 2,
  appBarStyle: FlexAppBarStyle.background,
  bottomAppBarElevation: 1.0,
  subThemesData: const FlexSubThemesData(
    useTextTheme: true,
    useM2StyleDividerInM3: true,
    thickBorderWidth: 2.0,
    filledButtonSchemeColor: SchemeColor.onSurface,
    elevatedButtonSchemeColor: SchemeColor.onPrimaryContainer,
    outlinedButtonSchemeColor: SchemeColor.onSurface,
    outlinedButtonOutlineSchemeColor: SchemeColor.onSurface,
    toggleButtonsBorderSchemeColor: SchemeColor.primary,
    segmentedButtonSchemeColor: SchemeColor.primary,
    segmentedButtonBorderSchemeColor: SchemeColor.primary,
    switchSchemeColor: SchemeColor.onSurface,
    checkboxSchemeColor: SchemeColor.inverseSurface,
    radioSchemeColor: SchemeColor.onSurface,
    unselectedToggleIsColored: true,
    sliderBaseSchemeColor: SchemeColor.onPrimaryContainer,
    inputDecoratorBackgroundAlpha: 153,
    inputDecoratorBorderSchemeColor: SchemeColor.tertiary,
    inputDecoratorRadius: 8.0,
    inputDecoratorUnfocusedHasBorder: false,
    inputDecoratorPrefixIconSchemeColor: SchemeColor.tertiary,
    fabUseShape: true,
    fabAlwaysCircular: true,
    fabSchemeColor: SchemeColor.onSurface,
    chipSelectedSchemeColor: SchemeColor.tertiaryContainer,
    popupMenuRadius: 8.0,
    dialogRadius: 16.0,
    dialogElevation: 1.0,
    datePickerHeaderBackgroundSchemeColor: SchemeColor.tertiaryContainer,
    datePickerDialogRadius: 16.0,
    timePickerDialogRadius: 16.0,
    timePickerElementRadius: 12.0,
    snackBarRadius: 8,
    snackBarBackgroundSchemeColor: SchemeColor.onPrimaryContainer,
    appBarScrolledUnderElevation: 0.0,
    tabBarItemSchemeColor: SchemeColor.scrim,
    tabBarUnselectedItemSchemeColor: SchemeColor.tertiary,
    tabBarUnselectedItemOpacity: 0.70,
    drawerIndicatorSchemeColor: SchemeColor.onSurface,
    drawerSelectedItemSchemeColor: SchemeColor.primaryContainer,
    drawerUnselectedItemSchemeColor: SchemeColor.tertiary,
    bottomSheetRadius: 16.0,
    bottomSheetModalElevation: 1.0,
    bottomNavigationBarSelectedLabelSchemeColor: SchemeColor.onSurface,
    bottomNavigationBarUnselectedLabelSchemeColor: SchemeColor.tertiary,
    bottomNavigationBarSelectedIconSchemeColor: SchemeColor.onSurface,
    bottomNavigationBarUnselectedIconSchemeColor: SchemeColor.tertiary,
    menuBarElevation: 1.0,
    menuBarShadowColor: Color(0x00000000),
    menuIndicatorBackgroundSchemeColor: SchemeColor.primaryContainer,
    menuIndicatorForegroundSchemeColor: SchemeColor.onPrimaryContainer,
    navigationBarSelectedLabelSchemeColor: SchemeColor.onSurface,
    navigationBarUnselectedLabelSchemeColor: SchemeColor.tertiary,
    navigationBarSelectedIconSchemeColor: SchemeColor.primaryContainer,
    navigationBarUnselectedIconSchemeColor: SchemeColor.tertiary,
    navigationBarIndicatorSchemeColor: SchemeColor.onSurface,
    navigationBarIndicatorOpacity: 1.00,
    navigationBarElevation: 1.0,
    navigationRailSelectedLabelSchemeColor: SchemeColor.onSurface,
    navigationRailUnselectedLabelSchemeColor: SchemeColor.tertiary,
    navigationRailSelectedIconSchemeColor: SchemeColor.primaryContainer,
    navigationRailUnselectedIconSchemeColor: SchemeColor.tertiary,
    navigationRailIndicatorSchemeColor: SchemeColor.onSurface,
    navigationRailIndicatorOpacity: 1.00,
  ),
  keyColors: const FlexKeyColors(
    useSecondary: true,
    useTertiary: true,
    keepPrimary: true,
    keepSecondary: true,
    keepTertiary: true,
  ),
  visualDensity: FlexColorScheme.comfortablePlatformDensity,
  useMaterial3: true,
  swapLegacyOnMaterial3: true,
  // To use the Playground font, add GoogleFonts package and uncomment
  // fontFamily: GoogleFonts.notoSans().fontFamily,
),
darkTheme: FlexThemeData.dark(
  colors: const FlexSchemeColor(
    primary: Color(0xffe0143f),
    primaryContainer: Color(0xff00325b),
    secondary: Color(0xffb9c8da),
    secondaryContainer: Color(0xff872100),
    tertiary: Color(0xffffb3b1),
    tertiaryContainer: Color(0xff004e59),
    appBarColor: Color(0xff872100),
    error: Color(0xffcf6679),
  ),
  surfaceMode: FlexSurfaceMode.highScaffoldLowSurface,
  blendLevel: 4,
  appBarStyle: FlexAppBarStyle.background,
  bottomAppBarElevation: 2.0,
  subThemesData: const FlexSubThemesData(
    blendTextTheme: true,
    useTextTheme: true,
    useM2StyleDividerInM3: true,
    thickBorderWidth: 2.0,
    filledButtonSchemeColor: SchemeColor.onSurface,
    elevatedButtonSchemeColor: SchemeColor.onPrimaryContainer,
    outlinedButtonSchemeColor: SchemeColor.onSurface,
    outlinedButtonOutlineSchemeColor: SchemeColor.onSurface,
    toggleButtonsBorderSchemeColor: SchemeColor.primary,
    segmentedButtonSchemeColor: SchemeColor.primary,
    segmentedButtonBorderSchemeColor: SchemeColor.primary,
    switchSchemeColor: SchemeColor.onSurface,
    checkboxSchemeColor: SchemeColor.inverseSurface,
    radioSchemeColor: SchemeColor.onSurface,
    unselectedToggleIsColored: true,
    sliderBaseSchemeColor: SchemeColor.onPrimaryContainer,
    inputDecoratorBackgroundAlpha: 153,
    inputDecoratorBorderSchemeColor: SchemeColor.tertiary,
    inputDecoratorRadius: 8.0,
    inputDecoratorUnfocusedHasBorder: false,
    inputDecoratorPrefixIconSchemeColor: SchemeColor.tertiary,
    fabUseShape: true,
    fabAlwaysCircular: true,
    fabSchemeColor: SchemeColor.onSurface,
    chipSelectedSchemeColor: SchemeColor.tertiaryContainer,
    popupMenuRadius: 8.0,
    dialogRadius: 16.0,
    dialogElevation: 1.0,
    datePickerHeaderBackgroundSchemeColor: SchemeColor.tertiaryContainer,
    datePickerDialogRadius: 16.0,
    timePickerDialogRadius: 16.0,
    timePickerElementRadius: 12.0,
    snackBarRadius: 8,
    snackBarBackgroundSchemeColor: SchemeColor.onPrimaryContainer,
    appBarScrolledUnderElevation: 0.0,
    tabBarItemSchemeColor: SchemeColor.inverseSurface,
    tabBarUnselectedItemOpacity: 0.70,
    tabBarIndicatorSchemeColor: SchemeColor.inversePrimary,
    drawerIndicatorSchemeColor: SchemeColor.onSurface,
    drawerSelectedItemSchemeColor: SchemeColor.primaryContainer,
    drawerUnselectedItemSchemeColor: SchemeColor.tertiary,
    bottomSheetRadius: 16.0,
    bottomSheetModalElevation: 1.0,
    bottomNavigationBarSelectedLabelSchemeColor: SchemeColor.onSurface,
    bottomNavigationBarUnselectedLabelSchemeColor: SchemeColor.tertiary,
    bottomNavigationBarSelectedIconSchemeColor: SchemeColor.onSurface,
    bottomNavigationBarUnselectedIconSchemeColor: SchemeColor.tertiary,
    menuBarElevation: 1.0,
    menuBarShadowColor: Color(0x00000000),
    menuIndicatorBackgroundSchemeColor: SchemeColor.primaryContainer,
    menuIndicatorForegroundSchemeColor: SchemeColor.onPrimaryContainer,
    navigationBarSelectedLabelSchemeColor: SchemeColor.onSurface,
    navigationBarUnselectedLabelSchemeColor: SchemeColor.tertiary,
    navigationBarSelectedIconSchemeColor: SchemeColor.primaryContainer,
    navigationBarUnselectedIconSchemeColor: SchemeColor.tertiary,
    navigationBarIndicatorSchemeColor: SchemeColor.onSurface,
    navigationBarIndicatorOpacity: 1.00,
    navigationBarElevation: 1.0,
    navigationRailSelectedLabelSchemeColor: SchemeColor.onSurface,
    navigationRailUnselectedLabelSchemeColor: SchemeColor.tertiary,
    navigationRailSelectedIconSchemeColor: SchemeColor.primaryContainer,
    navigationRailUnselectedIconSchemeColor: SchemeColor.tertiary,
    navigationRailIndicatorSchemeColor: SchemeColor.onSurface,
    navigationRailIndicatorOpacity: 1.00,
  ),
  keyColors: const FlexKeyColors(
    useSecondary: true,
    useTertiary: true,
    keepPrimary: true,
    keepSecondary: true,
    keepTertiary: true,
  ),
  visualDensity: FlexColorScheme.comfortablePlatformDensity,
  useMaterial3: true,
  swapLegacyOnMaterial3: true,
  // To use the Playground font, add GoogleFonts package and uncomment
  // fontFamily: GoogleFonts.notoSans().fontFamily,
),
// If you do not have a themeMode switch, uncomment this line
// to let the device system mode control the theme mode:
// themeMode: ThemeMode.system,
