// Theme config for FlexColorScheme version 7.1.x. Make sure you use
// same or higher package version, but still same major version. If you
// use a lower package version, some properties may not be supported.
// In that case remove them after copying this theme to your app.
theme: FlexThemeData.light(
  colors: const FlexSchemeColor(
    primary: Color(0xffbf0028),
    primaryContainer: Color(0xffffdad8),
    secondary: Color(0xff324151),
    secondaryContainer: Color(0xffffdbcf),
    tertiary: Color(0xff00aab4),
    tertiaryContainer: Color(0xffbcebef),
    appBarColor: Color(0xffffdbcf),
    error: Color(0xffb00020),
  ),
  surfaceMode: FlexSurfaceMode.highScaffoldLowSurface,
  blendLevel: 2,
  appBarStyle: FlexAppBarStyle.background,
  bottomAppBarElevation: 1.0,
  surfaceTint: const Color(0xff474747),
  subThemesData: const FlexSubThemesData(
    useTextTheme: true,
    useM2StyleDividerInM3: true,
    thickBorderWidth: 2.0,
    elevatedButtonSchemeColor: SchemeColor.onPrimaryContainer,
    outlinedButtonSchemeColor: SchemeColor.secondary,
    outlinedButtonOutlineSchemeColor: SchemeColor.secondary,
    toggleButtonsSchemeColor: SchemeColor.secondary,
    toggleButtonsBorderSchemeColor: SchemeColor.secondary,
    segmentedButtonSchemeColor: SchemeColor.secondary,
    segmentedButtonBorderSchemeColor: SchemeColor.secondary,
    switchSchemeColor: SchemeColor.secondary,
    switchThumbSchemeColor: SchemeColor.surface,
    checkboxSchemeColor: SchemeColor.secondary,
    radioSchemeColor: SchemeColor.secondary,
    sliderBaseSchemeColor: SchemeColor.secondary,
    inputDecoratorBackgroundAlpha: 153,
    inputDecoratorBorderSchemeColor: SchemeColor.secondary,
    inputDecoratorRadius: 8.0,
    inputDecoratorUnfocusedHasBorder: false,
    inputDecoratorPrefixIconSchemeColor: SchemeColor.secondary,
    fabUseShape: true,
    fabAlwaysCircular: true,
    chipSelectedSchemeColor: SchemeColor.secondaryContainer,
    popupMenuRadius: 8.0,
    tooltipSchemeColor: SchemeColor.onBackground,
    dialogRadius: 16.0,
    dialogElevation: 1.0,
    datePickerHeaderBackgroundSchemeColor: SchemeColor.onInverseSurface,
    datePickerDialogRadius: 16.0,
    timePickerDialogRadius: 16.0,
    timePickerElementRadius: 12.0,
    snackBarRadius: 8,
    snackBarBackgroundSchemeColor: SchemeColor.secondary,
    snackBarActionSchemeColor: SchemeColor.secondaryContainer,
    appBarScrolledUnderElevation: 0.0,
    tabBarItemSchemeColor: SchemeColor.scrim,
    tabBarUnselectedItemOpacity: 0.70,
    drawerIndicatorSchemeColor: SchemeColor.surfaceTint,
    drawerIndicatorOpacity: 0.1,
    drawerSelectedItemSchemeColor: SchemeColor.primary,
    bottomSheetRadius: 16.0,
    bottomSheetModalElevation: 1.0,
    menuBarElevation: 1.0,
    menuBarShadowColor: Color(0x00000000),
    menuIndicatorBackgroundSchemeColor: SchemeColor.surface,
    menuIndicatorForegroundSchemeColor: SchemeColor.primary,
    navigationBarSelectedLabelSchemeColor: SchemeColor.onSurface,
    navigationBarSelectedIconSchemeColor: SchemeColor.onPrimary,
    navigationBarIndicatorOpacity: 1.00,
    navigationBarElevation: 1.0,
    navigationRailSelectedLabelSchemeColor: SchemeColor.onSurface,
    navigationRailSelectedIconSchemeColor: SchemeColor.primary,
    navigationRailIndicatorSchemeColor: SchemeColor.onPrimary,
    navigationRailIndicatorOpacity: 1.00,
  ),
  keyColors: const FlexKeyColors(
    useSecondary: true,
    useTertiary: true,
    keepPrimary: true,
    keepSecondary: true,
    keepTertiary: true,
  ),
  visualDensity: FlexColorScheme.comfortablePlatformDensity,
  useMaterial3: true,
  swapLegacyOnMaterial3: true,
  // To use the Playground font, add GoogleFonts package and uncomment
  // fontFamily: GoogleFonts.notoSans().fontFamily,
),
darkTheme: FlexThemeData.dark(
  colors: const FlexSchemeColor(
    primary: Color(0xfff02954),
    primaryContainer: Color(0xff00325b),
    secondary: Color(0xffb9c8da),
    secondaryContainer: Color(0xff872100),
    tertiary: Color(0xff3be0eb),
    tertiaryContainer: Color(0xff004e59),
    appBarColor: Color(0xff872100),
    error: Color(0xffcf6679),
  ),
  surfaceMode: FlexSurfaceMode.highScaffoldLowSurface,
  blendLevel: 3,
  appBarStyle: FlexAppBarStyle.background,
  bottomAppBarElevation: 2.0,
  surfaceTint: const Color(0xff8f8f8f),
  subThemesData: const FlexSubThemesData(
    blendTextTheme: true,
    useTextTheme: true,
    useM2StyleDividerInM3: true,
    thickBorderWidth: 2.0,
    elevatedButtonSchemeColor: SchemeColor.onPrimaryContainer,
    outlinedButtonSchemeColor: SchemeColor.secondary,
    outlinedButtonOutlineSchemeColor: SchemeColor.secondary,
    toggleButtonsSchemeColor: SchemeColor.secondary,
    toggleButtonsBorderSchemeColor: SchemeColor.secondary,
    segmentedButtonSchemeColor: SchemeColor.secondary,
    segmentedButtonBorderSchemeColor: SchemeColor.secondary,
    switchSchemeColor: SchemeColor.secondary,
    switchThumbSchemeColor: SchemeColor.surface,
    checkboxSchemeColor: SchemeColor.secondary,
    radioSchemeColor: SchemeColor.secondary,
    sliderBaseSchemeColor: SchemeColor.secondary,
    inputDecoratorBackgroundAlpha: 153,
    inputDecoratorBorderSchemeColor: SchemeColor.secondary,
    inputDecoratorRadius: 8.0,
    inputDecoratorUnfocusedHasBorder: false,
    inputDecoratorPrefixIconSchemeColor: SchemeColor.secondary,
    fabUseShape: true,
    fabAlwaysCircular: true,
    chipSelectedSchemeColor: SchemeColor.secondaryContainer,
    popupMenuRadius: 8.0,
    tooltipSchemeColor: SchemeColor.onBackground,
    dialogRadius: 16.0,
    dialogElevation: 1.0,
    datePickerHeaderBackgroundSchemeColor: SchemeColor.onInverseSurface,
    datePickerDialogRadius: 16.0,
    timePickerDialogRadius: 16.0,
    timePickerElementRadius: 12.0,
    snackBarRadius: 8,
    snackBarBackgroundSchemeColor: SchemeColor.secondary,
    snackBarActionSchemeColor: SchemeColor.secondaryContainer,
    appBarScrolledUnderElevation: 0.0,
    tabBarItemSchemeColor: SchemeColor.inverseSurface,
    tabBarUnselectedItemOpacity: 0.70,
    tabBarIndicatorSchemeColor: SchemeColor.inversePrimary,
    drawerIndicatorSchemeColor: SchemeColor.surfaceTint,
    drawerIndicatorOpacity: 0.1,
    drawerSelectedItemSchemeColor: SchemeColor.primary,
    bottomSheetRadius: 16.0,
    bottomSheetModalElevation: 1.0,
    menuBarElevation: 1.0,
    menuBarShadowColor: Color(0x00000000),
    menuIndicatorBackgroundSchemeColor: SchemeColor.surface,
    menuIndicatorForegroundSchemeColor: SchemeColor.primary,
    navigationBarSelectedLabelSchemeColor: SchemeColor.onSurface,
    navigationBarSelectedIconSchemeColor: SchemeColor.onPrimary,
    navigationBarIndicatorOpacity: 1.00,
    navigationBarElevation: 1.0,
    navigationRailSelectedLabelSchemeColor: SchemeColor.onSurface,
    navigationRailSelectedIconSchemeColor: SchemeColor.primary,
    navigationRailIndicatorSchemeColor: SchemeColor.onPrimary,
    navigationRailIndicatorOpacity: 1.00,
  ),
  keyColors: const FlexKeyColors(
    useSecondary: true,
    useTertiary: true,
    keepPrimary: true,
    keepSecondary: true,
    keepTertiary: true,
  ),
  visualDensity: FlexColorScheme.comfortablePlatformDensity,
  useMaterial3: true,
  swapLegacyOnMaterial3: true,
  // To use the Playground font, add GoogleFonts package and uncomment
  // fontFamily: GoogleFonts.notoSans().fontFamily,
),
// If you do not have a themeMode switch, uncomment this line
// to let the device system mode control the theme mode:
// themeMode: ThemeMode.system,
