// Theme config for FlexColorScheme version 7.1.x. Make sure you use
// same or higher package version, but still same major version. If you
// use a lower package version, some properties may not be supported.
// In that case remove them after copying this theme to your app.
theme: FlexThemeData.light(
  colors: const FlexSchemeColor(
    primary: Color(0xff145ae1),
    primaryContainer: Color(0xffdbe1ff),
    secondary: Color(0xff5c5f72),
    secondaryContainer: Color(0xffdfe1f9),
    tertiary: Color(0xff006b5d),
    tertiaryContainer: Color(0xff95f0ff),
    appBarColor: Color(0xffdfe1f9),
    error: Color(0xffb00020),
  ),
  bottomAppBarElevation: 1.0,
  subThemesData: const FlexSubThemesData(
    interactionEffects: false,
    tintedDisabledControls: false,
    useTextTheme: true,
    outlinedButtonOutlineSchemeColor: SchemeColor.primary,
    toggleButtonsSchemeColor: SchemeColor.primaryContainer,
    toggleButtonsUnselectedSchemeColor: SchemeColor.onSurface,
    segmentedButtonSchemeColor: SchemeColor.primaryContainer,
    segmentedButtonBorderSchemeColor: SchemeColor.outline,
    radioSchemeColor: SchemeColor.secondary,
    sliderBaseSchemeColor: SchemeColor.secondary,
    inputDecoratorBackgroundAlpha: 166,
    inputDecoratorRadius: 8.0,
    inputDecoratorUnfocusedHasBorder: false,
    inputDecoratorPrefixIconSchemeColor: SchemeColor.primary,
    fabUseShape: true,
    fabAlwaysCircular: true,
    fabSchemeColor: SchemeColor.primary,
    chipSelectedSchemeColor: SchemeColor.primaryContainer,
    popupMenuRadius: 8.0,
    tooltipRadius: 8,
    tooltipSchemeColor: SchemeColor.inverseSurface,
    tooltipOpacity: 0.95,
    dialogRadius: 16.0,
    dialogElevation: 2.0,
    datePickerHeaderBackgroundSchemeColor: SchemeColor.primaryContainer,
    datePickerDialogRadius: 16.0,
    timePickerDialogRadius: 16.0,
    timePickerElementRadius: 12.0,
    snackBarRadius: 8,
    snackBarBackgroundSchemeColor: SchemeColor.onPrimaryContainer,
    tabBarItemSchemeColor: SchemeColor.primary,
    tabBarUnselectedItemOpacity: 0.75,
    drawerIndicatorOpacity: 0.6,
    drawerSelectedItemSchemeColor: SchemeColor.primary,
    bottomSheetRadius: 16.0,
    menuBarElevation: 2.0,
    menuBarShadowColor: Color(0x00000000),
    menuIndicatorBackgroundSchemeColor: SchemeColor.primaryContainer,
    navigationBarSelectedIconSchemeColor: SchemeColor.inversePrimary,
    navigationBarIndicatorOpacity: 1.00,
    navigationBarElevation: 1.0,
    navigationRailSelectedIconSchemeColor: SchemeColor.inversePrimary,
    navigationRailIndicatorOpacity: 1.00,
    navigationRailBackgroundSchemeColor: SchemeColor.surface,
  ),
  keyColors: const FlexKeyColors(
    useSecondary: true,
    useTertiary: true,
    keepPrimary: true,
    keepSecondary: true,
    keepTertiary: true,
  ),
  visualDensity: FlexColorScheme.comfortablePlatformDensity,
  useMaterial3: true,
  swapLegacyOnMaterial3: true,
  // To use the Playground font, add GoogleFonts package and uncomment
  // fontFamily: GoogleFonts.notoSans().fontFamily,
),
darkTheme: FlexThemeData.dark(
  colors: const FlexSchemeColor(
    primary: Color(0xffbdd1ff),
    primaryContainer: Color(0xff192ea0),
    secondary: Color(0xffb8bbe9),
    secondaryContainer: Color(0xff004d66),
    tertiary: Color(0xff82d5c6),
    tertiaryContainer: Color(0xff005046),
    appBarColor: Color(0xff004d66),
    error: Color(0xffcf6679),
  ),
  bottomAppBarElevation: 1.0,
  subThemesData: const FlexSubThemesData(
    interactionEffects: false,
    tintedDisabledControls: false,
    useTextTheme: true,
    outlinedButtonOutlineSchemeColor: SchemeColor.primary,
    toggleButtonsSchemeColor: SchemeColor.primaryContainer,
    toggleButtonsUnselectedSchemeColor: SchemeColor.onSurface,
    segmentedButtonSchemeColor: SchemeColor.primaryContainer,
    segmentedButtonBorderSchemeColor: SchemeColor.outline,
    radioSchemeColor: SchemeColor.secondary,
    sliderBaseSchemeColor: SchemeColor.secondary,
    inputDecoratorBackgroundAlpha: 128,
    inputDecoratorRadius: 8.0,
    inputDecoratorUnfocusedHasBorder: false,
    fabUseShape: true,
    fabAlwaysCircular: true,
    fabSchemeColor: SchemeColor.primary,
    chipSelectedSchemeColor: SchemeColor.primaryContainer,
    popupMenuRadius: 8.0,
    tooltipRadius: 8,
    tooltipSchemeColor: SchemeColor.inverseSurface,
    tooltipOpacity: 0.95,
    dialogRadius: 16.0,
    dialogElevation: 2.0,
    datePickerHeaderBackgroundSchemeColor: SchemeColor.primaryContainer,
    datePickerDialogRadius: 16.0,
    timePickerDialogRadius: 16.0,
    timePickerElementRadius: 12.0,
    snackBarRadius: 8,
    snackBarBackgroundSchemeColor: SchemeColor.onPrimaryContainer,
    tabBarItemSchemeColor: SchemeColor.primary,
    tabBarUnselectedItemSchemeColor: SchemeColor.onPrimaryContainer,
    tabBarUnselectedItemOpacity: 0.70,
    drawerIndicatorOpacity: 0.6,
    drawerSelectedItemSchemeColor: SchemeColor.primary,
    bottomSheetRadius: 16.0,
    menuBarElevation: 2.0,
    menuBarShadowColor: Color(0x00000000),
    menuIndicatorBackgroundSchemeColor: SchemeColor.primaryContainer,
    navigationBarSelectedIconSchemeColor: SchemeColor.inversePrimary,
    navigationBarIndicatorOpacity: 1.00,
    navigationBarElevation: 1.0,
    navigationRailSelectedIconSchemeColor: SchemeColor.inversePrimary,
    navigationRailIndicatorOpacity: 1.00,
    navigationRailBackgroundSchemeColor: SchemeColor.surface,
  ),
  keyColors: const FlexKeyColors(
    useSecondary: true,
    useTertiary: true,
    keepPrimary: true,
    keepSecondary: true,
    keepTertiary: true,
    keepPrimaryContainer: true,
  ),
  visualDensity: FlexColorScheme.comfortablePlatformDensity,
  useMaterial3: true,
  swapLegacyOnMaterial3: true,
  // To use the Playground font, add GoogleFonts package and uncomment
  // fontFamily: GoogleFonts.notoSans().fontFamily,
),
// If you do not have a themeMode switch, uncomment this line
// to let the device system mode control the theme mode:
// themeMode: ThemeMode.system,
