// Theme config for FlexColorScheme version 7.1.x. Make sure you use
// same or higher package version, but still same major version. If you
// use a lower package version, some properties may not be supported.
// In that case remove them after copying this theme to your app.
theme: FlexThemeData.light(
  colors: const FlexSchemeColor(
    primary: Color(0xff91d154),
    primaryContainer: Color(0xffc7ef9e),
    secondary: Color(0xff1a381b),
    secondaryContainer: Color(0xffd5e8cf),
    tertiary: Color(0xff57624a),
    tertiaryContainer: Color(0xff95f0ff),
    appBarColor: Color(0xffd5e8cf),
    error: Color(0xffb00020),
  ),
  bottomAppBarElevation: 2.0,
  subThemesData: const FlexSubThemesData(
    interactionEffects: false,
    tintedDisabledControls: false,
    useTextTheme: true,
    textButtonSchemeColor: SchemeColor.surfaceTint,
    elevatedButtonSchemeColor: SchemeColor.secondary,
    outlinedButtonSchemeColor: SchemeColor.secondary,
    outlinedButtonOutlineSchemeColor: SchemeColor.secondary,
    toggleButtonsSchemeColor: SchemeColor.primaryContainer,
    toggleButtonsUnselectedSchemeColor: SchemeColor.onSurface,
    segmentedButtonSchemeColor: SchemeColor.primaryContainer,
    radioSchemeColor: SchemeColor.secondary,
    sliderBaseSchemeColor: SchemeColor.secondary,
    inputDecoratorBackgroundAlpha: 153,
    inputDecoratorBorderSchemeColor: SchemeColor.secondary,
    inputDecoratorUnfocusedHasBorder: false,
    inputDecoratorPrefixIconSchemeColor: SchemeColor.secondary,
    fabUseShape: true,
    fabAlwaysCircular: true,
    chipSelectedSchemeColor: SchemeColor.primaryContainer,
    popupMenuRadius: 8.0,
    tooltipRadius: 8,
    tooltipSchemeColor: SchemeColor.inverseSurface,
    tooltipOpacity: 0.95,
    dialogRadius: 16.0,
    dialogElevation: 2.0,
    datePickerHeaderBackgroundSchemeColor: SchemeColor.primary,
    datePickerDialogRadius: 16.0,
    timePickerDialogRadius: 16.0,
    timePickerElementRadius: 12.0,
    snackBarRadius: 8,
    snackBarBackgroundSchemeColor: SchemeColor.onSecondaryContainer,
    tabBarItemSchemeColor: SchemeColor.secondary,
    tabBarUnselectedItemOpacity: 0.80,
    drawerIndicatorSchemeColor: SchemeColor.primary,
    bottomSheetRadius: 16.0,
    bottomNavigationBarSelectedLabelSchemeColor: SchemeColor.primary,
    bottomNavigationBarSelectedIconSchemeColor: SchemeColor.primary,
    menuBarElevation: 2.0,
    menuBarShadowColor: Color(0x00000000),
    menuIndicatorBackgroundSchemeColor: SchemeColor.primaryContainer,
    navigationBarSelectedIconSchemeColor: SchemeColor.onSecondary,
    navigationBarIndicatorOpacity: 1.00,
    navigationBarElevation: 1.0,
    navigationRailSelectedIconSchemeColor: SchemeColor.onSecondary,
    navigationRailIndicatorOpacity: 1.00,
    navigationRailBackgroundSchemeColor: SchemeColor.surface,
  ),
  keyColors: const FlexKeyColors(
    useSecondary: true,
    useTertiary: true,
    keepPrimary: true,
    keepSecondary: true,
    keepTertiary: true,
  ),
  visualDensity: FlexColorScheme.comfortablePlatformDensity,
  useMaterial3: true,
  swapLegacyOnMaterial3: true,
  // To use the Playground font, add GoogleFonts package and uncomment
  // fontFamily: GoogleFonts.notoSans().fontFamily,
),
darkTheme: FlexThemeData.dark(
  colors: const FlexSchemeColor(
    primary: Color(0xff91d154),
    primaryContainer: Color(0xff00325b),
    secondary: Color(0xffbfffab),
    secondaryContainer: Color(0xff872100),
    tertiary: Color(0xffbfcbae),
    tertiaryContainer: Color(0xff004e59),
    appBarColor: Color(0xff872100),
    error: Color(0xffcf6679),
  ),
  bottomAppBarElevation: 2.0,
  subThemesData: const FlexSubThemesData(
    interactionEffects: false,
    tintedDisabledControls: false,
    useTextTheme: true,
    textButtonSchemeColor: SchemeColor.surfaceTint,
    elevatedButtonSchemeColor: SchemeColor.secondary,
    outlinedButtonSchemeColor: SchemeColor.secondary,
    outlinedButtonOutlineSchemeColor: SchemeColor.secondary,
    toggleButtonsSchemeColor: SchemeColor.primaryContainer,
    toggleButtonsUnselectedSchemeColor: SchemeColor.onSurface,
    segmentedButtonSchemeColor: SchemeColor.primaryContainer,
    radioSchemeColor: SchemeColor.secondary,
    sliderBaseSchemeColor: SchemeColor.secondary,
    inputDecoratorBackgroundAlpha: 153,
    inputDecoratorUnfocusedHasBorder: false,
    fabUseShape: true,
    fabAlwaysCircular: true,
    chipSelectedSchemeColor: SchemeColor.primaryContainer,
    popupMenuRadius: 8.0,
    tooltipRadius: 8,
    tooltipSchemeColor: SchemeColor.inverseSurface,
    tooltipOpacity: 0.95,
    dialogRadius: 16.0,
    dialogElevation: 2.0,
    datePickerHeaderBackgroundSchemeColor: SchemeColor.primary,
    datePickerDialogRadius: 16.0,
    timePickerDialogRadius: 16.0,
    timePickerElementRadius: 12.0,
    snackBarRadius: 8,
    snackBarBackgroundSchemeColor: SchemeColor.onSecondaryContainer,
    tabBarItemSchemeColor: SchemeColor.secondary,
    drawerIndicatorSchemeColor: SchemeColor.primary,
    bottomSheetRadius: 16.0,
    bottomNavigationBarSelectedLabelSchemeColor: SchemeColor.primary,
    bottomNavigationBarSelectedIconSchemeColor: SchemeColor.primary,
    menuBarElevation: 2.0,
    menuBarShadowColor: Color(0x00000000),
    menuIndicatorBackgroundSchemeColor: SchemeColor.primaryContainer,
    navigationBarSelectedIconSchemeColor: SchemeColor.onSecondary,
    navigationBarIndicatorOpacity: 1.00,
    navigationBarElevation: 1.0,
    navigationRailSelectedIconSchemeColor: SchemeColor.onSecondary,
    navigationRailIndicatorOpacity: 1.00,
    navigationRailBackgroundSchemeColor: SchemeColor.surface,
  ),
  keyColors: const FlexKeyColors(
    useSecondary: true,
    useTertiary: true,
    keepPrimary: true,
    keepSecondary: true,
    keepTertiary: true,
  ),
  visualDensity: FlexColorScheme.comfortablePlatformDensity,
  useMaterial3: true,
  swapLegacyOnMaterial3: true,
  // To use the Playground font, add GoogleFonts package and uncomment
  // fontFamily: GoogleFonts.notoSans().fontFamily,
),
// If you do not have a themeMode switch, uncomment this line
// to let the device system mode control the theme mode:
// themeMode: ThemeMode.system,
